### ISSUE TITLE
如何运行life.cpp等文件

### ISSUE THREAD

**Issue by zcl0219** [Jack-Chan-2001/CS106B#1]
请问像life.cpp这些文件该如何运行呀？再创建一个Cmakelist吗？

**Comment by Jack-Chan-2001** [comment]
> 请问像life.cpp这些文件该如何运行呀？再创建一个Cmakelist吗？


有两种方法可以构建作业工程 life，您可以
直接用 Qt Creator 运行Life.pro文件；
或创建新 CMakeLists，参考 hello 示例工程把 Stanford CPP Lib 集成进来 O(∩_∩)O

**Comment by zcl0219** [comment]
> > 请问像life.cpp这些文件该如何运行呀？再创建一个Cmakelist吗？
> 
> 有两种方法可以构建作业工程 life，您可以 直接用 Qt Creator 运行Life.pro文件； 或创建新 CMakeLists，参考 hello 示例工程把 Stanford CPP Lib 集成进来 O(∩_∩)O

好的，了解了。非常感谢您的回复！
